import React,{useState} from 'react';
import { Heart,MessageCircle,Trash2 } from 'lucide-react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { backend } from '@/api/localBackend';
import { useAuth } from '@/lib/AuthContext';
import FounderBadge from '@/components/profile/FounderBadge';
import { formatDate } from '@/lib/utils';

export default function CommentSection({manhwaId,chapterId=null}){
  const {user}=useAuth(); const qc=useQueryClient(); const [text,setText]=useState(''),[spoiler,setSpoiler]=useState(false),[reply,setReply]=useState(null);
  const {data:comments=[]}=useQuery({queryKey:['comments',manhwaId,chapterId],queryFn:async()=>{const all=await backend.entities.Comment.list('-created_date');return all.filter(c=>c.manhwa_id===manhwaId&&(chapterId?c.chapter_id===chapterId:!c.chapter_id))}});
  const {data:badges=[]}=useQuery({queryKey:['allBadges'],queryFn:()=>backend.entities.UserBadge.list()});
  const create=useMutation({mutationFn:()=>backend.entities.Comment.create({manhwa_id:manhwaId,chapter_id:chapterId,user_email:user.email,user_name:user.name,user_avatar:user.avatar_url,content:text,parent_comment_id:reply,likes:0,liked_by:[],is_spoiler:spoiler}),onSuccess:()=>{setText('');setReply(null);qc.invalidateQueries({queryKey:['comments']})}});
  const remove=useMutation({mutationFn:id=>backend.entities.Comment.delete(id),onSuccess:()=>qc.invalidateQueries({queryKey:['comments']})});
  const like=useMutation({mutationFn:async c=>{const liked=c.liked_by?.includes(user.email);const liked_by=liked?c.liked_by.filter(x=>x!==user.email):[...(c.liked_by||[]),user.email];return backend.entities.Comment.update(c.id,{liked_by,likes:liked_by.length})},onSuccess:()=>qc.invalidateQueries({queryKey:['comments']})});
  const roots=comments.filter(c=>!c.parent_comment_id);
  const Card=({c,depth=0})=>{const founder=badges.some(b=>b.user_email===c.user_email&&b.badge_type==='founder');return <div className={`${depth?'ml-8 border-l border-zinc-800 pl-4':''} py-3`}><div className="flex gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-violet-600 to-fuchsia-600 font-bold">{c.user_name?.[0]}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-sm">{c.user_name}</b>{founder&&<FounderBadge/>}<span className="text-xs text-zinc-600">{formatDate(c.created_date)}</span></div><div className={`mt-2 rounded-xl bg-zinc-900/70 p-3 text-sm text-zinc-300 ${c.is_spoiler?'blur-sm hover:blur-none':''}`}>{c.content}</div><div className="mt-2 flex gap-3 text-xs text-zinc-500"><button onClick={()=>like.mutate(c)} className="flex items-center gap-1 hover:text-fuchsia-300"><Heart size={14}/>{c.likes||0}</button><button onClick={()=>setReply(c.id)} className="flex items-center gap-1 hover:text-violet-300"><MessageCircle size={14}/>Responder</button>{c.user_email===user.email&&<button onClick={()=>remove.mutate(c.id)} className="flex items-center gap-1 hover:text-red-300"><Trash2 size={14}/>Excluir</button>}</div></div></div>{comments.filter(x=>x.parent_comment_id===c.id).map(r=><Card key={r.id} c={r} depth={depth+1}/>)}</div>};
  return <section className="mt-10"><h2 className="font-display text-2xl font-bold">Comentários</h2><div className="mt-4 soft-card p-4">{reply&&<div className="mb-2 text-xs text-violet-300">Respondendo comentário · <button onClick={()=>setReply(null)}>cancelar</button></div>}<textarea value={text} onChange={e=>setText(e.target.value)} rows="3" placeholder="Escreva um comentário..." className="w-full resize-none rounded-xl border border-zinc-700 bg-zinc-950 p-3 outline-none focus:border-violet-500"/><div className="mt-3 flex items-center gap-3"><label className="flex items-center gap-2 text-xs text-zinc-400"><input type="checkbox" checked={spoiler} onChange={e=>setSpoiler(e.target.checked)}/> Spoiler</label><button disabled={!text.trim()} onClick={()=>create.mutate()} className="ml-auto rounded-xl bg-violet-600 px-4 py-2 text-sm font-bold disabled:opacity-40">Publicar</button></div></div><div className="mt-4 divide-y divide-zinc-800">{roots.map(c=><Card key={c.id} c={c}/>)}</div></section>;
}
