import React from 'react';
import {Link,useParams} from 'react-router-dom';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { backend } from '@/api/localBackend';
import { BookOpen,CheckCircle2,Circle,Eye,Share2,Star } from 'lucide-react';
import LibraryControls from '@/components/manhwa/LibraryControls';
import CommentSection from '@/components/manhwa/CommentSection';
import ReviewSection from '@/components/manhwa/ReviewSection';
import {formatNumber,statusLabel,typeLabel} from '@/lib/utils';
import {useAuth} from '@/lib/AuthContext';

export default function ManhwaDetail(){
 const {id}=useParams(),{user}=useAuth(),qc=useQueryClient();
 const {data:m}=useQuery({queryKey:['manhwa',id],queryFn:()=>backend.entities.Manhwa.get(id)});
 const {data:chapters=[]}=useQuery({queryKey:['chapters',id],queryFn:()=>backend.entities.Chapter.filter({manhwa_id:id})});
 const {data:history=[]}=useQuery({queryKey:['readingHistory',id,user?.email],queryFn:()=>backend.entities.ReadingHistory.filter({user_email:user.email,manhwa_id:id}),enabled:!!user});
 const toggle=useMutation({mutationFn:async c=>{const found=history.find(h=>h.chapter_id===c.id);return found?backend.entities.ReadingHistory.delete(found.id):backend.entities.ReadingHistory.create({user_email:user.email,manhwa_id:id,chapter_id:c.id,chapter_number:c.number,page_number:0,completed:true})},onSuccess:()=>qc.invalidateQueries({queryKey:['readingHistory'])});
 if(!m)return <div className="mx-auto max-w-7xl p-8">Carregando...</div>;
 const first=[...chapters].sort((a,b)=>a.number-b.number)[0];
 return <><section className="relative min-h-[520px] overflow-hidden"><img src={m.banner_image||m.cover_image} className="absolute inset-0 h-full w-full object-cover opacity-35"/><div className="absolute inset-0 bg-gradient-to-r from-zinc-950 via-zinc-950/80 to-transparent"/><div className="absolute inset-0 bg-gradient-to-t from-zinc-900 via-transparent to-transparent"/><div className="relative mx-auto flex max-w-7xl flex-col gap-7 px-4 py-16 md:flex-row md:items-end"><img src={m.cover_image} className="w-48 rounded-2xl border border-zinc-700 shadow-2xl sm:w-56"/><div className="max-w-3xl"><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-violet-500/20 px-3 py-1 text-violet-200">{typeLabel[m.type]}</span><span className="rounded-full bg-zinc-800 px-3 py-1">{statusLabel[m.status]}</span></div><h1 className="mt-4 font-display text-4xl font-extrabold sm:text-5xl">{m.title}</h1><div className="mt-3 flex gap-5 text-sm text-zinc-400"><span className="flex items-center gap-1"><Star size={16} className="text-yellow-400" fill="currentColor"/>{m.rating}</span><span className="flex items-center gap-1"><Eye size={16}/>{formatNumber(m.views)}</span><span>{chapters.length} capítulos</span></div><p className="mt-5 max-w-2xl text-zinc-300">{m.synopsis}</p><div className="mt-6 flex flex-wrap gap-2">{first&&<Link to={`/Reader/${m.id}/${first.id}`} className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-violet-600 to-fuchsia-600 px-5 py-3 font-bold"><BookOpen size={18}/>Começar a ler</Link>}<LibraryControls manhwaId={m.id}/><button onClick={()=>navigator.share?.({title:m.title,url:location.href})} className="rounded-xl border border-zinc-700 bg-zinc-900 px-3"><Share2/></button></div></div></div></section>
 <div className="mx-auto grid max-w-7xl gap-8 px-4 py-10 lg:grid-cols-[1fr_280px]"><div><h2 className="font-display text-2xl font-bold">Capítulos</h2><div className="mt-4 overflow-hidden rounded-2xl border border-zinc-800">{[...chapters].sort((a,b)=>b.number-a.number).map(c=>{const read=history.some(h=>h.chapter_id===c.id);return <Link key={c.id} to={`/Reader/${m.id}/${c.id}`} className="flex items-center gap-3 border-b border-zinc-800 p-4 last:border-0 hover:bg-zinc-800/40"><button onClick={e=>{e.preventDefault();e.stopPropagation();toggle.mutate(c)}} className={read?'text-violet-400':'text-zinc-600'}>{read?<CheckCircle2/>:<Circle/>}</button><div><b>Capítulo {c.number}</b><p className="text-xs text-zinc-500">{c.title}</p></div><span className="ml-auto text-xs text-zinc-600">{c.release_date}</span></Link>})}</div><CommentSection manhwaId={m.id}/><ReviewSection manhwaId={m.id}/></div><aside className="soft-card h-fit p-5 text-sm"><div className="space-y-4"><div><span className="text-zinc-500">Autor</span><p>{m.author}</p></div><div><span className="text-zinc-500">Artista</span><p>{m.artist}</p></div><div><span className="text-zinc-500">Ano</span><p>{m.release_year}</p></div><div><span className="text-zinc-500">Títulos alternativos</span><p>{m.alternative_titles||'—'}</p></div><div><span className="text-zinc-500">Gêneros</span><div className="mt-2 flex flex-wrap gap-2">{m.genres?.map(g=><Link key={g} to={`/Search?genre=${encodeURIComponent(g)}`} className="rounded-full bg-zinc-800 px-2 py-1 text-xs">{g}</Link>)}</div></div></div></aside></div></>;
}
