const L=(pt,en)=>({pt,en});

export const CLAN_META={
  version:'0.1153',
  checkedAt:'2026-09-06',
  clansUrl:'https://pocketants.fandom.com/wiki/Clans',
  joiningUrl:'https://pocketants.fandom.com/wiki/Joining_a_Clan_FAQ',
  coopUrl:'https://pocketants.fandom.com/wiki/Co-op_Mode',
  warsUrl:'https://pocketants.fandom.com/wiki/Clan_Wars',
  faqUrl:'https://pocketants.fandom.com/wiki/FAQ',
  officialUrl:'https://apps.apple.com/br/app/pocket-ants-colony-simulator/id1532712160',
  officialDiscord:'https://discord.gg/KFBTBRe'
};

export const CLAN_VISUAL={
  image:'https://cdn.aptoide.com/imgs/c/f/2/cf2a64e17329352b7159086e6d07b3cc_screen.jpg',
  source:'https://pocket-ants-ariel-software.en.aptoide.com/app',
  alt:L('Tela real de busca/ranking de clãs do Pocket Ants.','Real Pocket Ants clan search/ranking screen.'),
  caption:L('Exemplo real da área Social/Clãs mostrando busca, ranking, nível do clã, Queen e requisitos.','Real Social/Clans example showing search, ranking, clan level, Queen and requirements.')
};

export const CLAN_LEVELS=[
  {level:1,members:10,points:10000,donations:1,coopReward:1000},
  {level:2,members:12,points:25000,donations:1,coopReward:2000},
  {level:3,members:15,points:50000,donations:1,coopReward:3000},
  {level:4,members:20,points:100000,donations:1,coopReward:5000},
  {level:5,members:25,points:250000,donations:1,coopReward:7500},
  {level:6,members:30,points:500000,donations:2,coopReward:10000},
  {level:7,members:35,points:1000000,donations:2,coopReward:12500},
  {level:8,members:40,points:2000000,donations:2,coopReward:15000},
  {level:9,members:45,points:5000000,donations:2,coopReward:20000},
  {level:10,members:50,points:10000000,donations:2,coopReward:25000},
  {level:11,members:55,points:20000000,donations:2,coopReward:35000},
  {level:12,members:60,points:50000000,donations:3,coopReward:null},
  {level:13,members:60,points:null,donations:3,coopReward:null},
  {level:14,members:60,points:null,donations:3,coopReward:null},
  {level:15,members:60,points:null,donations:3,coopReward:null}
];

export const CLAN_BONUS_TIERS=[
  {min:1,max:5,speed:20,fusion:2,costEach:250000},
  {min:6,max:11,speed:30,fusion:3,costEach:400000},
  {min:12,max:15,speed:40,fusion:5,costEach:500000}
];

export const CLAN_BONUSES=[
  {id:'worker-speed',icon:'🐜',name:L('Velocidade das trabalhadoras','Worker speed')},
  {id:'player-speed',icon:'🏃',name:L('Velocidade do jogador','Player speed')},
  {id:'soldier-speed',icon:'⚔️',name:L('Velocidade dos soldados','Soldier speed')},
  {id:'soldier-resilience',icon:'🛡️',name:L('Resistência dos soldados','Soldier resilience')},
  {id:'fusion',icon:'🧬',name:L('Chance de sucesso da fusão','Fusion success chance')}
];

export const CLAN_ROLES=[
  {id:'larva',icon:'🥚',name:L('Larva','Larva'),facts:[L('Envia mensagens, pede recursos e doa ao armazenamento do clã.','Can chat, request resources and donate to clan storage.'),L('Pode doar criaturas/flores para a base, participar de Clan Wars, doar a membros e entrar no co-op do clã.','Can donate creatures/flowers to the base, participate in Clan Wars, donate to members and join clan co-op.')]},
  {id:'worker',icon:'🐜',name:L('Worker','Worker'),facts:[L('Tem tudo da Larva.','Has all Larva permissions.'),L('Pode visualizar/atacar a base do clã e fazer friendly battles.','Can view/attack the clan base and run friendly battles.')]},
  {id:'major',icon:'🎖️',name:L('Major','Major'),facts:[L('Gerencia pedidos de entrada, convida membros e edita a descrição.','Manages join requests, invites members and edits the description.'),L('Pode expulsar Larvas/Workers e alterar cores de membros compatíveis.','Can kick Larvae/Workers and change allowed member colors.')]},
  {id:'supermajor',icon:'⭐',name:L('Supermajor','Supermajor'),facts:[L('Tem as permissões de Major.','Has Major permissions.'),L('Pode ativar bônus e abrir/hostear co-ops do clã.','Can activate bonuses and open/host clan co-ops.'),L('O clã pode ter no máximo 2 Supermajors.','A clan can have at most 2 Supermajors.')]},
  {id:'queen',icon:'👑',name:L('Queen','Queen'),facts:[L('É a líder e principal administradora do clã.','The clan leader and main administrator.'),L('Edita logo, requisitos, modo de entrada, base e Superqueen.','Edits logo, requirements, join mode, base and Superqueen.'),L('Registra/cancela Clan Wars, envia mensagens do clã, promove/demove Supermajors e pode transferir a liderança.','Registers/cancels Clan Wars, sends clan messages, promotes/demotes Supermajors and can transfer leadership.'),L('Pode dissolver o clã.','Can dissolve the clan.')]} 
];

export const CLAN_WAR_SCHEDULE=[
  {day:L('Sexta 00:00–22:00 UTC','Friday 00:00–22:00 UTC'),title:L('Registro','Registration'),text:L('A Queen registra o clã e escolhe 12v12, 25v25 ou 50v50 e os participantes. Registrar consome Fungus, Leaves e Seeds.','The Queen registers the clan, chooses 12v12, 25v25 or 50v50 and selects participants. Registration consumes Fungus, Leaves and Seeds.')},
  {day:L('Sexta 22:00–23:59 UTC','Friday 22:00–23:59 UTC'),title:L('Matchmaking','Matchmaking'),text:L('O jogo pareia por tier e poder geral.','The game pairs clans by tier and overall power.')},
  {day:L('Sábado','Saturday'),title:L('Preparação','Preparation'),text:L('Organize defesa pessoal, alvos e estratégia do clã.','Organize personal defense, targets and clan strategy.')},
  {day:L('Domingo','Sunday'),title:L('Guerra','War'),text:L('Cada participante recebe 3 ataques: 2 ninhos inimigos + 1 Superqueen/base inimiga.','Each participant gets 3 attacks: 2 enemy nests + 1 enemy Superqueen/base attack.')},
  {day:L('Segunda até o próximo registro','Monday until next registration'),title:L('Resultados e coleta','Results and claims'),text:L('Recompensas pessoais e do clã precisam ser coletadas manualmente antes da próxima janela de registro.','Personal and clan rewards must be claimed manually before the next registration window.')}
];

const S={clans:[CLAN_META.clansUrl],joining:[CLAN_META.clansUrl,CLAN_META.joiningUrl],coop:[CLAN_META.coopUrl,CLAN_META.clansUrl],wars:[CLAN_META.warsUrl,CLAN_META.clansUrl],faq:[CLAN_META.faqUrl,CLAN_META.joiningUrl]};

export const CLAN_RECORDS=[
  {id:'overview',icon:'🏳️',category:'basics',title:L('Clãs: visão geral','Clans: overview'),summary:L('Sistema social com chat, doações, bônus temporários, co-op, base própria e Clan Wars.','Social system with chat, donations, temporary bonuses, clan co-op, a shared base and Clan Wars.'),facts:[L('Clãs começam no nível 1 e o nível máximo documentado é 15.','Clans start at level 1 and the documented maximum level is 15.'),L('O nome do clã é único e não pode ser alterado depois de criado; o logo pode ser editado.','Clan names are unique and cannot be changed after creation; the logo can be edited.'),L('Os troféus do clã são a soma dos troféus dos membros multiplicada pelo nível do clã.','Clan trophies are the sum of member trophies multiplied by the clan level.'),L('O menu Social reúne Clan, Chat, Bonus, Search e Co-op; versões recentes também possuem War.','The Social menu includes Clan, Chat, Bonus, Search and Co-op; recent versions also include War.')],sources:S.clans},
  {id:'joining',icon:'🔎',category:'recruitment',title:L('Entrar e encontrar um clã','Joining and finding a clan'),summary:L('Entenda troféus/QC, modo aberto, pedidos, convites e como avaliar exigências antes de entrar.','Understand trophies/QC, open/request mode, invites and how to evaluate requirements before joining.'),facts:[L('A Queen define requisito mínimo de Queen Chamber e troféus para entrada pela busca.','The Queen sets minimum Queen Chamber and trophy requirements for joining through search.'),L('Um convite direto de Queen/Major pode ignorar requisitos de QC/troféus.','A direct invite from clan leadership can bypass QC/trophy requirements.'),L('A busca interna exige o nome completo para encontrar clãs fora do ranking; não diferencia maiúsculas/minúsculas.','In-game search requires the full name to find clans outside the ranking and is case-insensitive.'),L('O FAQ recomenda o canal de recrutamento do Discord porque normalmente mostra horário de co-op e exigência de doação antes de você entrar.','The FAQ recommends the Discord recruitment channel because it often shows co-op times and donation rules before you join.'),L('Leia o quadro de descrição assim que entrar: muitos clãs colocam idioma, horário de co-op, doação e limite de inatividade ali.','Read the clan description board immediately: many clans list language, co-op time, donations and inactivity limits there.')],sources:S.joining},
  {id:'levels',icon:'📈',category:'progression',title:L('Níveis, capacidade e ranking','Levels, capacity and ranking'),summary:L('Tabela de membros, Clan Points necessários e efeito do nível sobre doações/co-op.','Member capacity, Clan Points requirements and how level affects donations/co-op.'),facts:[L('Capacidade cresce de 10 membros no Lv1 até 60 a partir do Lv12.','Capacity grows from 10 members at Lv1 to 60 from Lv12 onward.'),L('A barra de atividade usa Clan Points; o requisito registrado no Lv12 é 50.000.000.','The activity bar uses Clan Points; the documented Lv12 requirement is 50,000,000.'),L('Membros inativos por mais de 30 dias aparecem como 1.000 troféus para o cálculo do ranking do clã até voltarem a logar.','Members inactive for over 30 days count as 1,000 trophies for clan ranking until they log back in.')],sources:S.clans},
  {id:'roles',icon:'👑',category:'management',title:L('Cargos e permissões','Roles and permissions'),summary:L('Larva, Worker, Major, Supermajor e Queen possuem permissões progressivas de gestão.','Larva, Worker, Major, Supermajor and Queen have progressively stronger management permissions.'),facts:[L('Larvas já podem doar, pedir recursos, participar de wars e entrar em clan co-op.','Larvae can already donate, request resources, participate in wars and join clan co-op.'),L('Supermajors podem ativar bônus e hostear clan co-op.','Supermajors can activate bonuses and host clan co-op.'),L('Queen controla requisitos, base/Superqueen e registro de Clan Wars.','The Queen controls requirements, base/Superqueen and Clan War registration.')],sources:S.clans},
  {id:'donations',icon:'📦',category:'economy',title:L('Doações ao armazenamento do clã','Donations to clan storage'),summary:L('Fungus, Leaves e Seeds alimentam bônus e sistemas do clã; a quantidade doada é livre, mas há limite de tentativas por dia.','Fungus, Leaves and Seeds fund clan bonuses and systems; donation amount is free but daily donation attempts are limited.'),facts:[L('Lv1–5: 1 doação ao armazenamento por dia.','Lv1–5: 1 clan-storage donation per day.'),L('Lv6–11: 2 doações por dia.','Lv6–11: 2 donations per day.'),L('Lv12+: a referência atual registra 3 doações por dia.','Lv12+: the current reference records 3 donations per day.'),L('Você escolhe quanto colocar em Fungus, Leaves e Seeds; o jogo limita pelo que você possui/capacidade.','You choose how much Fungus, Leaves and Seeds to donate; the game is limited by what you hold/can store.'),L('A estatística “Total donation” soma doações ao clã e a outros membros.','The “Total donation” stat includes donations to clan storage and other members.')],sources:S.clans},
  {id:'requests',icon:'🤲',category:'economy',title:L('Pedir e doar recursos entre membros','Resource requests between members'),summary:L('Membros podem pedir Fungus, Leaves ou Seeds uma vez por dia e outros podem preencher o pedido.','Members can request Fungus, Leaves or Seeds once per day and others can fill the request.'),facts:[L('A capacidade do pedido equivale a 20% do limite da câmara correspondente, com máximo documentado de 1.999 nos storages Lv12.','Request capacity equals 20% of the corresponding chamber cap, with a documented maximum of 1,999 at Lv12 storage.'),L('Só um pedido pode ficar ativo; um pedido novo pode substituir o anterior.','Only one request can remain active; a new request can replace the previous one.'),L('Há cooldown de 20 s para a mesma pessoa doar novamente no mesmo pedido, mas ajudar outros membros não tem limite diário documentado.','There is a 20-second cooldown before the same player can donate again to the same request, but helping other members has no documented daily limit.')],sources:S.clans},
  {id:'bonuses',icon:'⬆️',category:'economy',title:L('Bônus do clã','Clan bonuses'),summary:L('Cinco buffs de 7 dias usam o armazenamento coletivo e escalam com o nível do clã.','Five 7-day buffs use shared storage and scale with clan level.'),facts:[L('Bônus: velocidade das trabalhadoras, velocidade do jogador, velocidade dos soldados, resistência dos soldados e chance de fusão.','Bonuses: worker speed, player speed, soldier speed, soldier resilience and fusion success.'),L('Queen ou Supermajor ativa; o efeito começa imediatamente e vale para todos os membros.','Queen or Supermajor activates them; effects start immediately and apply to every member.'),L('Lv1–5: +20% nos quatro bônus de velocidade/resistência e +2% fusão; 250.000 de cada Fungus/Leaves/Seeds por bônus.','Lv1–5: +20% speed/resilience and +2% fusion; 250,000 each Fungus/Leaves/Seeds per bonus.'),L('Lv6–11: +30% / +3%; 400.000 de cada recurso por bônus.','Lv6–11: +30% / +3%; 400,000 of each resource per bonus.'),L('Lv12+: +40% / +5%; 500.000 de cada recurso por bônus.','Lv12+: +40% / +5%; 500,000 of each resource per bonus.'),L('Vários bônus podem ficar ativos ao mesmo tempo.','Multiple bonuses can be active at the same time.')],sources:S.clans},
  {id:'clan-points',icon:'🎯',category:'progression',title:L('Clan Points e barra de atividade','Clan Points and activity bar'),summary:L('Pheromones, anúncios de Battle Tokens e clan co-op alimentam a progressão do clã.','Pheromones, Battle Token ads and clan co-op feed clan progression.'),facts:[L('Atividade individual: 1 Clan Point por pheromone obtido em ataques/Dr. Zany.','Individual activity: 1 Clan Point per pheromone obtained from attacks/Dr. Zany.'),L('Assistir anúncio de Battle Token também rende 1 Clan Point.','Watching a Battle Token ad also gives 1 Clan Point.'),L('Clan co-op dá uma recompensa grande de Clan Points que escala com o nível do clã até Lv11.','Clan co-op gives a large Clan Point reward that scales with clan level through Lv11.'),L('No Lv12, clan co-op passa a dar 15.000 Fungus + 15.000 Leaves + 15.000 Seeds ao armazenamento por co-op em vez de Clan Points.','At Lv12, clan co-op instead gives 15,000 Fungus + 15,000 Leaves + 15,000 Seeds to storage per co-op rather than Clan Points.')],sources:[...S.clans,...S.coop]},
  {id:'clan-coop',icon:'🤝',category:'coop',title:L('Clan Co-op','Clan Co-op'),summary:L('Uma segunda oportunidade diária de Termite/Crab, sem código, aberta pela liderança e mais difícil que a pública.','A second daily Termite/Crab opportunity, no code required, opened by leadership and harder than public co-op.'),facts:[L('Termite e Crab podem ser vencidos uma vez por dia no modo do clã, separadamente do co-op público.','Termite and Crab can each be completed once per day in clan mode, separate from public co-op.'),L('Queen e Supermajors podem abrir/hostear o lobby segundo a documentação atual.','Queen and Supermajors can open/host the lobby according to the current documentation.'),L('Todos os membros online recebem aviso quando o lobby abre.','All online members are notified when the lobby opens.'),L('Não há código de sala e não existe limite documentado de participantes do próprio clã.','No room code is required and there is no documented clan-member participant cap.'),L('Membro recém-chegado só pode entrar após o próximo reset de 00:00 UTC.','A newly joined member can only participate after the next 00:00 UTC reset.'),L('Termite: 2.000 Resin + 30 min sem termites; Crab: 100 Body Parts + 1 ponto de Crab.','Termite: 2,000 Resin + 30 minutes without termites; Crab: 100 Body Parts + 1 Crab point.')],sources:S.coop},
  {id:'clan-wars',icon:'⚔️',category:'war',title:L('Clan Wars','Clan Wars'),summary:L('Ciclo semanal com registro, preparação, 3 ataques por participante, Silk e recompensas coletadas manualmente.','Weekly cycle with registration, preparation, 3 attacks per participant, Silk and manually claimed rewards.'),facts:[L('Tiers: 12v12, 25v25 e 50v50.','Tiers: 12v12, 25v25 and 50v50.'),L('Domingo: 2 ataques a ninhos inimigos + 1 ataque à Superqueen/base.','Sunday: 2 enemy-nest attacks + 1 Superqueen/base attack.'),L('O vencedor é definido pela porcentagem total de destruição contra o clã adversário.','The winner is determined by total destruction percentage against the opposing clan.'),L('Recompensas pessoais incluem Silk escalada por contribuição, tier e resultado.','Personal rewards include Silk scaled by contribution, tier and outcome.'),L('O clã também pode receber Silk, Clan XP e um bônus temporário exclusivo da guerra.','The clan can also receive Silk, Clan XP and a temporary exclusive war bonus.'),L('Recompensas precisam ser coletadas antes do próximo registro; as não coletadas são perdidas.','Rewards must be claimed before the next registration; unclaimed rewards are lost.')],sources:S.wars},
  {id:'base',icon:'🏰',category:'war',title:L('Base do clã e Superqueen','Clan base and Superqueen'),summary:L('Área social/defensiva personalizável usada nas Clan Wars, com exército, flores defensivas e Superqueen.','Customizable social/defensive space used in Clan Wars, with army units, defensive flowers and Superqueen.'),facts:[L('A base aceita mais de 50 unidades/obstáculos posicionáveis livremente.','The base supports more than 50 freely placed units/obstacles.'),L('Criaturas e flores defensivas precisam ser desbloqueadas por doações dos membros.','Creatures and defensive flowers must be unlocked through member donations.'),L('A primeira pessoa que desbloqueia uma unidade fica registrada no painel da unidade.','The first member to unlock a unit is permanently credited on its info panel.'),L('A Superqueen pode ser aprimorada, receber cor e nickname usando recursos do clã.','The Superqueen can be upgraded, recolored and nicknamed using clan resources.')],sources:S.wars},
  {id:'chat',icon:'💬',category:'social',title:L('Chat, recrutamento e status','Chat, recruitment and status'),summary:L('Chat possui mensagens de membros/sistema, pedidos de recursos, status online e recrutamento.','Chat includes member/system messages, resource requests, online status and recruitment.'),facts:[L('Mensagens de membro têm limite documentado de 150 caracteres.','Member messages have a documented 150-character limit.'),L('O chat reseta diariamente às 00:00 UTC e possui limite de histórico.','Clan chat resets daily at 00:00 UTC and has a history limit.'),L('Cores de membro aparecem no chat, pedidos e co-op.','Member colors appear in chat, requests and co-op.'),L('A Queen pode usar o megafone para enviar recrutamento a jogadores que atendem aos requisitos.','The Queen can use the megaphone to send recruitment messages to eligible players.'),L('Requests de entrada mostram nome, QC e troféus; a referência documenta até 15 requests simultâneos.','Join requests show name, QC and trophies; the reference documents up to 15 simultaneous requests.')],sources:S.clans},
  {id:'create-manage',icon:'🛠️',category:'management',title:L('Criar, editar e gerenciar um clã','Creating and managing a clan'),summary:L('Criar exige QC5+, 50 Gems e 250 Honeydew; nome é permanente e a gestão diária pode ser trabalhosa.','Creating requires QC5+, 50 Gems and 250 Honeydew; the name is permanent and day-to-day management can be demanding.'),facts:[L('Requisito para criar: Queen Chamber Lv5 ou superior.','Creation requirement: Queen Chamber Lv5 or higher.'),L('Custo documentado: 50 Gems + 250 Honeydew.','Documented cost: 50 Gems + 250 Honeydew.'),L('O nome precisa ser único e não pode ser alterado depois.','The name must be unique and cannot be changed later.'),L('Logo, requisitos de entrada e modo open/request podem ser configurados pela Queen.','Logo, join requirements and open/request mode can be configured by the Queen.'),L('A própria referência avisa que administrar um clã sério exige esforço e que normalmente é mais fácil entrar em um já existente.','The reference itself notes that running a serious clan takes effort and joining an existing clan is usually easier.')],sources:S.clans}
];

export const CLAN_CATEGORIES=['all','basics','recruitment','progression','management','economy','coop','war','social'];

export function clanRecord(id){return CLAN_RECORDS.find(item=>item.id===id)||null;}
export function clanLevel(level){return CLAN_LEVELS.find(row=>row.level===Number(level))||CLAN_LEVELS[0];}
export function clanBonusTier(level){return CLAN_BONUS_TIERS.find(row=>Number(level)>=row.min&&Number(level)<=row.max)||CLAN_BONUS_TIERS[2];}
