const ALL_CREATURES_VIDEO = 'https://www.youtube.com/watch?v=ubfv-IkrBuk';
const ALL_CREATURES_THUMB = 'https://img.youtube.com/vi/ubfv-IkrBuk/hqdefault.jpg';

const ytSearch = (name) => `https://www.youtube.com/results?search_query=${encodeURIComponent(`Pocket Ants ${name} guide capture`)}`;
const fandom = (slug) => `https://pocketants.fandom.com/wiki/${slug}`;

export const catalogMeta = {
  checkedAt: '2026-09-05',
  gameVersion: '0.1153',
  note: 'Dados cruzados com materiais oficiais, wiki comunitária indexada e vídeos. Campos com fonte incompleta aparecem como “A revisar”.',
  official: 'https://play.google.com/store/apps/details?id=com.ariel.zanyants',
  generalGuide: ALL_CREATURES_VIDEO
};

const normal = ({id,name,rarity,variantOf=null,roles=[],stats={},bodyParts,captureTime,attraction,description,obtain=[],battleNotes=[],sourceSlug,video=null,image=null,verification='high'}) => ({
  id,name,category:'normal',rarity,variantOf,roles,stats,bodyParts,captureTime,attraction,description,obtain,battleNotes,
  verification,verifiedAt:'2026-09-05',sourceUrl:fandom(sourceSlug),
  imageUrl:image || ALL_CREATURES_THUMB,
  imageLabel:image ? 'Imagem de vídeo/tutorial específico' : 'Imagem do guia geral de criaturas',
  videos: video ? [video,{title:'Guia geral de todas as criaturas',url:ALL_CREATURES_VIDEO,creator:'Rupar',type:'geral'}] : [{title:'Guia geral de todas as criaturas',url:ALL_CREATURES_VIDEO,creator:'Rupar',type:'geral'}],
  youtubeSearchUrl:ytSearch(name)
});

export const normalCreatures = [
  normal({id:'tarantula',name:'Tarantula',rarity:'Comum',roles:['Corpo a corpo','Início'],stats:{damage:4,health:33,attackRate:52,speed:36},bodyParts:20,captureTime:'30 s',attraction:'Qualquer horário e qualquer clima',description:'Criatura comum e uma das primeiras que o jogador encontra. É simples de derrotar e útil para começar a montar o exército ou conseguir Body Parts.',obtain:['Construa a Creatures Chamber.','Use qualquer feromônio para atrair uma criatura.','A Tarantula pode aparecer em qualquer horário e clima.','Derrote-a e escolha capturar em vez de coletar a carcaça.'],battleNotes:['Boa criatura temporária no começo, mas é superada rapidamente por opções raras e especiais.'],sourceSlug:'Tarantula'}),
  normal({id:'praying-mantis',name:'Praying Mantis',rarity:'Comum',roles:['Dano','Início'],stats:{health:22,attackRate:62,speed:50},bodyParts:20,captureTime:'30 s',attraction:'Qualquer horário; condição de clima sem restrição conhecida',description:'Mantis comum de dano. É uma opção de early game para quem ainda não tem criaturas raras ou de evento.',obtain:['Use feromônios depois de construir a Creatures Chamber.','Pode ser atraída sem condição especial de evento.','Derrote e capture.'],battleNotes:['A comunidade costuma trocá-la por Scorpion, Centipede ou criaturas especiais assim que possível.'],sourceSlug:'Praying_Mantis',verification:'medium'}),
  normal({id:'tiger-beetle',name:'Tiger Beetle',rarity:'Incomum',roles:['Dano','Sniper','Velocidade'],stats:{damage:4,health:22,attackRate:72,speed:96},bodyParts:20,captureTime:'1 min',attraction:'Qualquer horário e qualquer clima segundo a página individual atual',description:'Extremamente rápida e capaz de saltar em alvos. É uma das criaturas mais velozes entre as normais.',obtain:['Use feromônios.','Não exige item especial nem evento.','Derrote e capture.'],battleNotes:['Pode pular sobre soldados e alcançar alvos rapidamente.','Boa para pressão, mas tem pouca vida.'],sourceSlug:'Tiger_Beetle'}),
  normal({id:'scorpion',name:'Scorpion',rarity:'Incomum',roles:['Dano','Sniper'],stats:{damage:4,health:33,attackRate:88,speed:50},bodyParts:20,captureTime:'1 min',attraction:'Crepúsculo ou noite; qualquer clima',description:'Uma das melhores opções normais do começo por combinar ataque alto com obtenção relativamente simples.',obtain:['Espere crepúsculo/noite.','Use feromônios.','Derrote e capture.'],battleNotes:['É muito citado pela comunidade como upgrade natural sobre Tarantula/Mantis no early game.'],sourceSlug:'Scorpion'}),
  normal({id:'butterfly',name:'Butterfly',rarity:'Incomum',roles:['Cura','Suporte','Voadora'],stats:{damage:0,health:22,attackRate:59,speed:24},bodyParts:20,captureTime:'2 min',attraction:'Dia ou amanhecer; qualquer clima',description:'Criatura pacifista: não causa dano e cura criaturas aliadas com rajadas de partículas aproximadamente a cada alguns segundos.',obtain:['Atraia durante o dia ou amanhecer.','Para derrotá-la, espere anoitecer: ela pousa e pode ser atacada.','Capture após derrotar.'],battleNotes:['Em PvP, segue aliados feridos e os cura.','Pode atrasar bastante uma luta quando o Attack Rate é melhorado.'],sourceSlug:'Butterfly'}),
  normal({id:'bombardier-beetle',name:'Bombardier Beetle',rarity:'Rara',roles:['Tanque','Controle de grupo','Área'],stats:{damage:10,health:44,attackRate:17,speed:14},bodyParts:60,captureTime:'2 min',attraction:'Sem condição especial confirmada na página atual; aparece entre as raras normais',description:'Besouro lento com ataque químico em área. É especialmente perigoso para grupos de soldados.',obtain:['Use feromônios para tentar uma criatura rara.','Derrote com cuidado para não perder muitos soldados.','Capture na Creatures Chamber.'],battleNotes:['Muito útil em defesa e controle de grupo.'],sourceSlug:'Bombardier_Beetle'}),
  normal({id:'rhinoceros-beetle',name:'Rhinoceros Beetle',rarity:'Rara',roles:['Tanque','Área'],stats:{damage:8,health:81,attackRate:55,speed:9},bodyParts:80,captureTime:'2 min',attraction:'Crepúsculo/noite; qualquer clima',description:'Uma das criaturas normais mais resistentes. É muito lenta, mas aguenta bastante dano e possui golpe amplo.',obtain:['Tente a atração no crepúsculo ou à noite.','Use feromônios.','Derrote e capture.'],battleNotes:['Ótima parede de vida; mobilidade é o ponto fraco.'],sourceSlug:'Rhinoceros_Beetle'}),
  normal({id:'dragonfly',name:'Dragonfly',rarity:'Rara',roles:['Voadora','Dano','Sniper'],stats:{damage:16,health:33,attackRate:45,speed:52},bodyParts:20,captureTime:'2 min',attraction:'Somente durante chuva ou neve; qualquer horário',description:'Criatura voadora rara com bom dano. A condição climática é o principal obstáculo para obtê-la.',obtain:['Espere chuva ou neve.','Use feromônios enquanto o clima estiver ativo.','Derrote e capture.'],battleNotes:['Pode atacar outras criaturas voadoras.','Natal costuma facilitar tentativas porque a neve substitui chuva em alguns eventos.'],sourceSlug:'Dragonfly'}),
  normal({id:'hornet',name:'Hornet',rarity:'Rara',roles:['Voadora','Dano'],stats:{damage:16,health:44,attackRate:42,speed:48},bodyParts:60,captureTime:'1 min',attraction:'Exige Honeycomb da Beehive',description:'Rara voadora que não aparece por um summon comum: é preciso sair da Beehive segurando Honeycomb e então usar feromônios.',obtain:['Entre na Beehive usando Bee Essence.','Complete o labirinto, adormeça a Queen Bee com Geranium e pegue o Honeycomb.','Saia da Beehive ainda segurando o Honeycomb.','Use qualquer feromônio: o Honeycomb é consumido e o Hornet aparece.','Golden summon + Honeycomb pode gerar Golden Hornet.'],battleNotes:['Boa criatura de começo/meio.','Jogadores atuais alertam que perde valor quando adversários passam a usar Frog, que é forte contra voadores.'],sourceSlug:'Asian_Giant_Hornet',video:{title:'How to capture Asian Giant Hornet',url:'https://www.youtube.com/watch?v=GUq3OXDP_l8',creator:'Smart Daddy',type:'dedicado'},image:'https://img.youtube.com/vi/GUq3OXDP_l8/hqdefault.jpg'}),
  normal({id:'centipede',name:'Centipede',rarity:'Rara',roles:['Corpo a corpo','Dano'],stats:{damage:4,health:44,attackRate:88,speed:32},bodyParts:60,captureTime:'2 min',attraction:'Crepúsculo ou noite; qualquer clima',description:'Criatura terrestre com combinação muito forte de vida e velocidade de ataque para uma normal.',obtain:['Espere crepúsculo/noite.','Use feromônios.','Derrote e capture.'],battleNotes:['É uma das opções normais mais recomendadas para jogadores que ainda não têm especiais.'],sourceSlug:'Centipede'}),
  normal({id:'crab',name:'Crab',rarity:'Lendária',roles:['Tanque','Área','Co-op'],stats:{damage:80,health:81,attackRate:17,speed:32},bodyParts:null,captureTime:'Instantâneo',attraction:'Não usa feromônios; vem da barra do Crab Beach Co-op',description:'Primeira criatura lendária. Tem ataque lento, muita vida e dano enorme em área.',obtain:['Jogue e vença Crab Beach Co-op.','Cada ponto preenche a barra de atividade do Crab.','A wiki comunitária registra no máximo 2 pontos/dia sem reset extra: um público e um de clã.','Com a barra completa e vaga livre, use o botão para adicionar um Crab 1★ ao exército.'],battleNotes:['É excelente como tanque e pode eliminar criaturas fracas em um golpe.'],sourceSlug:'Crab_(creature)',video:{title:'The Full Crab Co-op Guide',url:'https://www.youtube.com/watch?v=TQHjlIGAZZ8',creator:'CowyTree',type:'dedicado'},image:'https://img.youtube.com/vi/TQHjlIGAZZ8/hqdefault.jpg'}),
  normal({id:'frog',name:'Frog',rarity:'Lendária',roles:['Anti-aéreo','Área','Co-op'],stats:{damage:24,health:81,attackRate:81,speed:32},bodyParts:null,captureTime:'Instantâneo',attraction:'Não usa feromônios; vem da barra do Frog Pond Co-op',description:'Lendária especializada em eliminar voadores. Sua língua pode executar criaturas aéreas no alcance; quando não há alvo aéreo, usa ataque em área.',obtain:['Jogue Frog Pond Co-op.','Ganhe pontos para a barra de atividade do Frog.','A referência comunitária registra 1 ponto por dia sem resets, levando no mínimo cerca de 10 dias.','Com a barra completa e slot livre, adicione o Frog 1★.'],battleNotes:['Um dos motivos pelos quais Hornet perde valor no PvP avançado.'],sourceSlug:'Frog_(creature)',verification:'high'})
];

const eventCreature = ({id,name,event,year,variantOf='—',description,ability=null,stats={},bodyParts=null,captureTime='A revisar',roles=[],sourceSlug,video=null,image=null,verification='medium',extraObtain=[]}) => ({
  id,name,category:'event',rarity:'Especial',variantOf,roles,stats,bodyParts,captureTime,
  attraction:'Barra de atividade do evento / mini-evento quando disponível',
  description,ability,eventHistory:[`${event} ${year}`],
  obtain:[`Durante ${event} ${year}, complete a barra de atividade do evento.`,...extraObtain,'Derrote a criatura e capture-a se houver vaga.','Em Creature Events/mini-events antigos, algumas especiais retornam e normalmente não têm limite diário.'],
  verification,verifiedAt:'2026-09-05',sourceUrl:fandom(sourceSlug),
  imageUrl:image || ALL_CREATURES_THUMB,
  imageLabel:image ? 'Imagem de vídeo/tutorial específico' : 'Imagem do guia geral de criaturas',
  videos:video?[video,{title:'Guia geral de criaturas',url:ALL_CREATURES_VIDEO,creator:'Rupar',type:'geral'}]:[{title:'Guia geral de criaturas',url:ALL_CREATURES_VIDEO,creator:'Rupar',type:'geral'}],
  youtubeSearchUrl:ytSearch(name)
});

export const eventCreatures = [
  eventCreature({id:'ghost-mantis',name:'Ghost Mantis',event:'Halloween',year:2020,variantOf:'Praying Mantis',roles:['Dano','Sniper'],description:'Uma das primeiras especiais do jogo. É uma Mantis com atributos muito superiores, especialmente Attack Rate.',sourceSlug:'Ghost_Mantis'}),
  eventCreature({id:'christmas-spider',name:'Christmas Spider',event:'Christmas',year:2020,variantOf:'Tarantula',roles:['Dano','Sniper'],description:'Variante natalina da Tarantula com atributos aumentados e presença histórica forte nos primeiros eventos.',sourceSlug:'Christmas_Spider',video:{title:'Christmas Spider VS Other Creatures',url:'https://www.youtube.com/watch?v=w05anfdR_a8',creator:'Lamman',type:'dedicado'},image:'https://img.youtube.com/vi/w05anfdR_a8/hqdefault.jpg'}),
  eventCreature({id:'paussinae-beetle',name:'Paussinae Beetle',event:"Valentine's",year:2021,variantOf:'Bombardier Beetle',roles:['Tanque','Controle de grupo'],stats:{damage:10,health:61,attackRate:26,speed:21},bodyParts:60,captureTime:'2 min',description:'Especial de controle de grupo. Possui projétil temático de coração e atributos superiores ao Bombardier normal.',sourceSlug:'Paussinae_Beetle'}),
  eventCreature({id:'monarch-butterfly',name:'Monarch Butterfly',event:'Easter',year:2021,variantOf:'Butterfly',roles:['Cura','Suporte','Voadora'],description:'Variante especial curandeira. Retorna em Creature Events e precisa pousar para ser atacada.',sourceSlug:'Monarch_Butterfly',extraObtain:['Em mini-eventos recentes, o limite diário pode ser removido enquanto o evento estiver ativo.']}),
  eventCreature({id:'festive-tiger-beetle',name:'Festive Tiger Beetle',event:'Anniversary',year:2021,variantOf:'Tiger Beetle',roles:['Dano','Sniper'],description:'Tiger Beetle comemorativo com mais vida e Attack Rate que o normal.',sourceSlug:'Festive_Tiger_Beetle'}),
  eventCreature({id:'halloween-pennant',name:'Halloween Pennant',event:'Halloween',year:2021,variantOf:'Dragonfly',roles:['Voadora','Dano','Sniper'],description:'Especial voadora baseada na Dragonfly, com vida e dano maiores.',sourceSlug:'Halloween_Pennant'}),
  eventCreature({id:'christmas-beetle',name:'Christmas Beetle',event:'Christmas',year:2021,variantOf:'Rhinoceros Beetle',roles:['Tanque','Área'],description:'Rhino Beetle especial com vida extremamente alta, pensado para tankar e causar dano em área.',sourceSlug:'Christmas_Beetle'}),
  eventCreature({id:'shocking-pink-dragon-millipede',name:'Shocking Pink Dragon Millipede',event:"Valentine's",year:2022,variantOf:'Centipede',roles:['Corpo a corpo','Dano'],description:'Variante especial da Centipede introduzida no evento de Valentine de 2022 e reexibida em mini-events.',sourceSlug:'Shocking_Pink_Dragon_Millipede'}),
  eventCreature({id:'orchid-mantis',name:'Orchid Mantis',event:'Easter',year:2022,variantOf:'Praying Mantis',roles:['Dano','Sniper'],description:'Mantis especial com Attack Rate e vida muito superiores à versão comum.',sourceSlug:'Orchid_Mantis'}),
  eventCreature({id:'emperor-scorpion',name:'Emperor Scorpion',event:'Anniversary',year:2022,variantOf:'Scorpion',roles:['Corpo a corpo','Dano','Sniper'],description:'Scorpion especial muito mais resistente que o normal e presença recorrente em listas de boas especiais terrestres.',sourceSlug:'Emperor_Scorpion'}),
  eventCreature({id:'emerald-cockroach-wasp',name:'Emerald Cockroach Wasp',event:'Summer',year:2022,variantOf:'Hornet',roles:['Voadora','Dano','Sniper'],description:'Vespa especial voadora com Attack Rate muito alto.',sourceSlug:'Emerald_Cockroach_Wasp'}),
  eventCreature({id:'skull-spider',name:'Skull Spider',event:'Halloween',year:2022,variantOf:'Tarantula',roles:['Corpo a corpo','Dano','Sniper'],description:'Aranha especial de Halloween com vida e Attack Rate superiores à Tarantula.',sourceSlug:'Skull_Spider'}),
  eventCreature({id:'red-costate-tiger-moth',name:'Red Costate Tiger Moth',event:'Christmas',year:2022,variantOf:'Butterfly',roles:['Cura','Suporte','Voadora'],description:'Moth especial de suporte, com melhores atributos que a Butterfly.',sourceSlug:'Red_Costate_Tiger_Moth'}),
  eventCreature({id:'roseate-skimmer',name:'Roseate Skimmer Dragonfly',event:"Valentine's",year:2023,variantOf:'Dragonfly',roles:['Voadora','Dano','Sniper'],description:'Dragonfly especial com mais velocidade e vida.',sourceSlug:'Roseate_Skimmer_Dragonfly'}),
  eventCreature({id:'flower-chafer',name:'Flower Chafer Beetle',event:'Easter',year:2023,variantOf:'Rhinoceros Beetle',roles:['Tanque'],description:'Rhino especial com mais velocidade e vida. Seus Creature Events tiveram edições confirmadas inclusive em 2025 e 2026.',sourceSlug:'Flower_Chafer_Beetle'}),
  eventCreature({id:'manticora',name:'Manticora Tiger Beetle',event:'Anniversary',year:2023,variantOf:'Tiger Beetle',roles:['Sniper','Dano'],description:'Tiger Beetle especial com Attack Rate e vida maiores; retornou em mini-event.',sourceSlug:'Manticora_Tiger_Beetle'}),
  eventCreature({id:'trilobite',name:'Trilobite Beetle',event:'Summer',year:2023,variantOf:'Centipede',roles:['Corpo a corpo','Dano'],stats:{damage:5,health:69,attackRate:99,speed:61},bodyParts:60,captureTime:'2 min',description:'Uma das especiais terrestres mais fortes da geração 2023, com vida alta e Attack Rate quase máximo.',sourceSlug:'Trilobite_Beetle'}),
  eventCreature({id:'lugubrious',name:'Lugubrious Bombardier Beetle',event:'Halloween',year:2023,variantOf:'Bombardier Beetle',roles:['Tanque','Controle de grupo'],stats:{damage:10,health:61,attackRate:33,speed:25},bodyParts:60,captureTime:'2 min',description:'Bombardier especial mais resistente e veloz, mantendo forte utilidade de controle.',sourceSlug:'Lugubrious_Bombardier_Beetle'}),
  eventCreature({id:'antlered-wasp',name:'Antlered Wasp',event:'Christmas',year:2023,variantOf:'Dragonfly',roles:['Voadora','Dano'],stats:{damage:31,health:67,attackRate:59,speed:55},bodyParts:60,captureTime:'1 min',description:'Vespa especial com ataque muito forte, inclusive contra outros voadores.',sourceSlug:'Antlered_Wasp'}),
  eventCreature({id:'christmas-crab',name:'Christmas Crab',event:'Christmas',year:2023,variantOf:'Crab',roles:['Lendária especial','Tanque','Área'],description:'Variante especial do Crab. Não é obtida como uma especial comum: exige barra própria de co-op e um Crab Token ligado às criaturas do evento natalino.',sourceSlug:'Christmas_Crab_(creature)',extraObtain:['Além da barra do Christmas Crab Co-op, é preciso obter um Crab Token; em 2023/2024/2025 ele foi ligado à coleta de 5 criaturas natalinas específicas.'],verification:'high'}),
  eventCreature({id:'red-scorpion',name:'Red Scorpion',event:"Valentine's",year:2024,variantOf:'Scorpion',roles:['Corpo a corpo','Dano'],description:'Scorpion especial de Valentine 2024, uma das variantes terrestres de alto desempenho.',sourceSlug:'Red_Scorpion'}),
  eventCreature({id:'jeweled-flower-mantis',name:'Jeweled Flower Mantis',event:'Easter',year:2024,variantOf:'Praying Mantis',roles:['Dano','Sniper'],description:'Mantis especial com vida e velocidade muito maiores que a versão normal.',sourceSlug:'Jeweled_Flower_Mantis'}),
  eventCreature({id:'cyanide-millipede',name:'Cyanide Millipede',event:'Anniversary',year:2024,variantOf:'Centipede',roles:['Corpo a corpo','Dano'],description:'Millipede especial com nuvem tóxica que acrescenta dano e pode eliminar formigas.',ability:'Nuvem tóxica',sourceSlug:'Cyanide_Millipede'}),
  eventCreature({id:'common-eastern-firefly',name:'Common Eastern Firefly',event:'Summer',year:2024,variantOf:'Attack Beetle / classificação comunitária',roles:['Dano','Tanque','Voadora à noite'],description:'Alterna comportamento: atacante terrestre durante o dia e voador à noite.',sourceSlug:'Common_Eastern_Firefly',verification:'medium'}),
  eventCreature({id:'halloween-hisser',name:'Halloween Hisser',event:'Halloween',year:2024,variantOf:'Rhinoceros Beetle',roles:['Tanque','Área'],description:'Rhino especial com Attack Speed e vida maiores. A habilidade Hiss causa dano extra e pode matar formigas.',ability:'Hiss',sourceSlug:'Halloween_Hisser'}),
  eventCreature({id:'december-moth',name:'December Moth',event:'Christmas',year:2024,variantOf:'Butterfly',roles:['Cura','Suporte','Voadora'],stats:{health:67,attackRate:72,speed:41},bodyParts:20,captureTime:'2 min',description:'Moth pacifista: não ataca, mas cura aliados. Foi a criatura principal do Christmas Event 2024.',sourceSlug:'December_Moth'}),
  eventCreature({id:'red-paper-wasp',name:'Red Paper Wasp',event:"Valentine's",year:2025,variantOf:'Hornet / Dragonfly-like',roles:['Voadora','Dano'],stats:{health:67,attackRate:59,speed:60},bodyParts:60,captureTime:'1 min',description:'Vespa vermelha com dano muito alto e boa atuação contra voadores.',ability:'Sting',sourceSlug:'Red_Paper_Wasp'}),
  eventCreature({id:'ladybug',name:'Ladybug',event:'Easter',year:2025,variantOf:'Attack Beetle / Tiger Beetle-like',roles:['Tanque','Dano'],stats:{health:100,attackRate:100,speed:55},bodyParts:20,captureTime:'1 min',description:'Uma das especiais mais resistentes, com escudo temporário que bloqueia dano e recarrega mais rápido conforme as estrelas.',ability:'Poison Shield',sourceSlug:'Ladybug'}),
  eventCreature({id:'black-widow',name:'Black Widow',event:'5th Anniversary',year:2025,variantOf:'Tarantula',roles:['Dano','Tanque'],stats:{damage:5,health:100,attackRate:100,speed:68},bodyParts:20,captureTime:'1 min',description:'Aranha especial do 5º aniversário, com vida e Attack Rate máximos segundo a página comunitária atual.',sourceSlug:'Black_Widow',verification:'medium'}),
  eventCreature({id:'beach-tiger-beetle',name:'Beach Tiger Beetle',event:'Summer',year:2025,variantOf:'Tiger Beetle',roles:['Velocidade','Dano','Ambush'],stats:{damage:5,health:67,attackRate:100,speed:100},bodyParts:20,captureTime:'1 min',description:'Extremamente rápida. Periodicamente recebe uma aura azul que aumenta ainda mais seu desempenho.',ability:'Speed / aura azul',sourceSlug:'Beach_Tiger_Beetle'}),
  eventCreature({id:'african-deaths-head-hawkmoth',name:"African Death's-Head Hawkmoth",event:'Halloween',year:2025,variantOf:'Butterfly',roles:['Cura','Suporte','Voadora'],stats:{health:67,attackRate:72,speed:37},captureTime:'2 min',description:'Moth curandeira com Toxic Spores: além de curar aliados, pode causar dano em criaturas próximas quando a habilidade ativa.',ability:'Toxic Spores',sourceSlug:'African_Death%E2%80%99s-Head_Hawkmoth'}),
  eventCreature({id:'white-faced-meadowhawk',name:'White-faced Meadowhawk',event:'Christmas',year:2025,variantOf:'Dragonfly',roles:['Voadora','Dano','Velocidade'],stats:{damage:31,health:67,attackRate:59,speed:54},description:'Dragonfly especial com alta vida e Attack Rate. Possui aura de velocidade que acelera movimento e ataques.',ability:'Speed / aura azul',sourceSlug:'White-faced_Meadowhawk'}),
  eventCreature({id:'fire-millipede',name:'Fire Millipede',event:"Valentine's",year:2026,variantOf:'Centipede',roles:['Corpo a corpo','Dano','Área'],stats:{damage:5,health:69,attackRate:99,speed:58},description:'Uma das especiais mais fortes registradas em 2026. Deixa uma trilha de fogo que permanece por alguns segundos e causa dano pesado.',ability:'Fire Trail',sourceSlug:'Fire_Millipede',video:{title:'Fire Millipede vs Top Creatures',url:'https://www.youtube.com/watch?v=wrA4nbjgzl4',creator:'Smart Daddy',type:'dedicado'},image:'https://img.youtube.com/vi/wrA4nbjgzl4/hqdefault.jpg'}),
  eventCreature({id:'peacock-spider',name:'Peacock Spider',event:'Easter',year:2026,variantOf:'Tarantula',roles:['Controle de grupo','Dano'],stats:{health:75,attackRate:100,speed:74},description:'Aranha especial de Easter 2026. Quando a barra roxa enche, executa uma dança que atordoa criaturas inimigas próximas.',ability:'Hypnotic Dance',sourceSlug:'Peacock_spider',extraObtain:['O evento principal exigia 1000 pontos e permitia 2 atrações por dia.']}),
  eventCreature({id:'asian-giant-hornet-special',name:'Asian Giant Hornet (Especial)',event:'6th Anniversary',year:2026,variantOf:'Hornet',roles:['Voadora','Dano'],description:'Nova especial do 6º aniversário de 2026. A wiki ainda marca parte dos stats como placeholder; por isso números não são tratados como definitivos aqui.',sourceSlug:'Asian_giant_hornet',verification:'review',video:{title:'Pocket Ants 6th Anniversary Event — new special creature',url:'https://www.youtube.com/watch?v=nCR3wOheRr4',creator:'BATTLE LOOK GAMING',type:'evento'},image:'https://img.youtube.com/vi/nCR3wOheRr4/hqdefault.jpg'})
];

export const allCatalogCreatures = [...normalCreatures, ...eventCreatures];

export const acquisitionFilters = [
  {id:'all',label:'Todas'},
  {id:'normal',label:'Feromônios / normais'},
  {id:'event',label:'Eventos'},
  {id:'coop',label:'Co-op'},
  {id:'special-item',label:'Item especial'}
];

export function acquisitionKind(creature){
  if(creature.id==='crab'||creature.id==='frog'||creature.id==='christmas-crab') return 'coop';
  if(creature.id==='hornet') return 'special-item';
  return creature.category==='event'?'event':'normal';
}
