import React,{useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowRight,BookOpen,Check,ChevronLeft,ChevronRight,ExternalLink,Filter,Search,ShieldCheck,Sparkles,Target,Waypoints} from 'lucide-react';
import {useLanguage} from './LanguageProviderLite';
import {GUIDE_CATEGORIES,GUIDE_GOALS,GUIDE_META,GUIDE_RECORDS,GUIDE_SOURCE_LABELS,GUIDE_STAGE_ROUTES} from './guideResearchData';
import './resourceDatabasePage.css';
import './guideDatabasePage.css';

const tr=(v,l)=>v&&typeof v==='object'?(l==='en'?v.en:v.pt):v;
const norm=(v='')=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const byId=id=>GUIDE_RECORDS.find(g=>g.id===id);
const stageRank={early:0,'early-mid':1,mid:2,'mid-late':3,late:4};
const progressKey=id=>`pa-guide-progress-${id}`;

function readHeaderQuery(){return new URLSearchParams((window.location.hash.split('?')[1]||'')).get('dbq')||'';}
function stageLabel(v,t){return ({early:t('Início','Early'),'early-mid':t('Início / meio','Early / mid'),mid:t('Meio','Mid'),'mid-late':t('Meio / avançado','Mid / late'),late:t('Avançado','Late')})[v]||v;}
function categoryLabel(v,t){return ({all:t('Todos','All'),progression:t('Progressão','Progression'),economy:t('Economia','Economy'),farm:'Farm',creatures:t('Criaturas','Creatures'),coop:'Co-op',garden:t('Jardim','Garden'),combat:t('Combate','Combat'),clan:t('Clã','Clan'),late:'Late game'})[v]||v;}
function sourceLabel(v,language){return tr(GUIDE_SOURCE_LABELS[v]||GUIDE_SOURCE_LABELS.reviewed,language);}

function GoalRouter({language,t}){
  const [goal,setGoal]=useState('start');
  const route=GUIDE_GOALS[goal];
  return <section className="rdb-panel gd-goal-panel"><div className="gd-panel-head"><div><span><Target size={16}/>{t('Escolha pelo problema','Choose by problem')}</span><h2>{t('O que você quer resolver agora?','What do you want to solve now?')}</h2></div></div><div className="gd-goal-tabs">{Object.entries(GUIDE_GOALS).map(([id,g])=><button key={id} type="button" className={goal===id?'active':''} onClick={()=>setGoal(id)}>{tr(g.label,language)}</button>)}</div><div className="gd-route-flow">{route.ids.map((id,i)=>{const g=byId(id);return <React.Fragment key={id}><a href={`#/guides/${id}`}><span>{g.icon}</span><div><small>{i+1}</small><strong>{tr(g.title,language)}</strong></div></a>{i<route.ids.length-1&&<ArrowRight size={16}/>}</React.Fragment>;})}</div></section>;
}

function StageRoutes({language,t}){return <section className="rdb-panel"><div className="gd-panel-head"><div><span><Waypoints size={16}/>{t('Por fase','By stage')}</span><h2>{t('Não sabe onde começar?','Not sure where to start?')}</h2></div></div><div className="gd-stage-grid">{Object.entries(GUIDE_STAGE_ROUTES).map(([id,route])=><div key={id}><b>{tr(route.label,language)}</b><small>{route.ids.length} {t('guias','guides')}</small><div>{route.ids.slice(0,3).map(gid=>{const g=byId(gid);return <a key={gid} href={`#/guides/${gid}`}>{g.icon} {tr(g.title,language)} <ChevronRight size={14}/></a>})}</div></div>)}</div></section>}

function SourceBadge({guide,language}){const official=guide.source==='official';return <span className={`gd-source ${guide.source}`}>{official?<ShieldCheck size={13}/>:guide.source==='recent'?<Sparkles size={13}/>:<BookOpen size={13}/>} {sourceLabel(guide.source,language)}</span>}

function GuideCard({guide,language,t}){return <article className="rdb-card gd-card"><div className="rdb-card-top"><span className="rdb-icon">{guide.icon}</span><div className="rdb-card-badges"><span>{categoryLabel(guide.category,t)}</span><span>{stageLabel(guide.stage,t)}</span></div></div><div className="rdb-card-head"><div><h2>{tr(guide.title,language)}</h2><small>{tr(guide.outcome,language)}</small></div></div><p className="rdb-summary">{tr(guide.summary,language)}</p><div className="gd-card-meta"><span><b>{guide.steps.length}</b>{t('passos','steps')}</span><span><b>{guide.avoid.length}</b>{t('erros a evitar','mistakes to avoid')}</span></div><div className="rdb-card-actions"><a className="rdb-open" href={`#/guides/${guide.id}`}>{t('Abrir guia','Open guide')} <ChevronRight size={15}/></a><SourceBadge guide={guide} language={language}/></div></article>}

function GuideList(){
  const {language,t}=useLanguage();
  const [query,setQuery]=useState(readHeaderQuery);
  const [category,setCategory]=useState('all');
  const [stage,setStage]=useState('all');
  useEffect(()=>{const fn=()=>setQuery(readHeaderQuery());window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);
  const filtered=useMemo(()=>GUIDE_RECORDS.filter(g=>{const hay=norm([tr(g.title,language),tr(g.summary,language),tr(g.outcome,language),...g.steps.map(x=>tr(x,language)),...g.avoid.map(x=>tr(x,language))].join(' '));return(!query||hay.includes(norm(query)))&&(category==='all'||g.category===category)&&(stage==='all'||g.stage===stage)}).sort((a,b)=>(stageRank[a.stage]??9)-(stageRank[b.stage]??9)),[query,category,stage,language]);
  return <div className="rdb-page gd-page"><section className="rdb-identity gd-identity"><div className="rdb-title-row"><span className="rdb-db-icon"><BookOpen size={22}/></span><div><span className="rdb-kicker">{t('Guias · decisão antes de informação','Guides · decisions before information')}</span><h1>{t('Central de Guias','Guides Hub')}</h1></div></div><p>{t('Rotas curtas por fase e objetivo, com passos marcáveis, erros comuns e links para os bancos de dados. Leia só o que resolve seu problema agora.','Short routes by stage and goal, with checkable steps, common mistakes and links to the databases. Read only what solves your problem now.')}</p><div className="rdb-principles"><span><Target size={15}/>{t('Objetivo primeiro','Goal first')}</span><span><Check size={15}/>{t('Passos marcáveis','Checkable steps')}</span><span><ShieldCheck size={15}/>{t('Fonte visível','Visible sources')}</span></div></section>
  <section className="gd-update"><Sparkles size={18}/><div><b>{t(`Base v${GUIDE_META.version} · revisada em 06/09/2026`,`Database v${GUIDE_META.version} · reviewed 2026-09-06`)}</b><span>{t('Estratégias comunitárias ficam rotuladas e separadas de regras documentadas.','Community strategies stay labeled and separate from documented rules.')}</span></div><a href={GUIDE_META.officialUrl} target="_blank" rel="noreferrer">{t('Jogo oficial','Official game')} <ExternalLink size={13}/></a></section>
  <GoalRouter language={language} t={t}/><StageRoutes language={language} t={t}/>
  <nav className="rdb-tabs" aria-label={t('Categorias de guias','Guide categories')}>{GUIDE_CATEGORIES.map(c=><button key={c} type="button" className={category===c?'active':''} onClick={()=>setCategory(c)}>{categoryLabel(c,t)}</button>)}</nav>
  <div className="rdb-filter-row"><label className="rdb-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('Buscar Resin, fusão, co-op, clã…','Search Resin, fusion, co-op, clan…')}/></label><details className="rdb-filters"><summary><Filter size={16}/>{t('Filtros','Filters')} <span>{filtered.length}</span></summary><div><label><span>{t('Fase','Stage')}</span><select value={stage} onChange={e=>setStage(e.target.value)}><option value="all">{t('Todas','All')}</option><option value="early">{t('Início','Early')}</option><option value="early-mid">{t('Início / meio','Early / mid')}</option><option value="mid">{t('Meio','Mid')}</option><option value="mid-late">{t('Meio / avançado','Mid / late')}</option><option value="late">{t('Avançado','Late')}</option></select></label></div></details></div>
  <div className="rdb-result-line"><b>{filtered.length}</b> {t('guias encontrados','guides found')}</div>{filtered.length?<section className="rdb-grid gd-grid">{filtered.map(g=><GuideCard key={g.id} guide={g} language={language} t={t}/>)}</section>:<div className="rdb-empty"><Search size={28}/><b>{t('Nenhum guia encontrado','No guide found')}</b></div>}</div>;
}

function LinkGroup({title,ids,type,t}){if(!ids?.length)return null;const label=id=>({leaves:t('Folhas','Leaves'),fungus:t('Fungo','Fungus'),seeds:t('Sementes','Seeds'),resin:t('Resina','Resin'),'body-parts':t('Partes de criatura','Creature Parts'),honeydew:'Honeydew','battle-tokens':'Battle Tokens',pheromones:t('Feromônios','Pheromones'),gems:t('Gemas','Gems'),water:t('Água','Water'),silk:t('Seda','Silk'),queen:t('Câmara da rainha',"Queen's Chamber"),resin:t('Resina','Resin'),creatures:t('Câmara de criaturas','Creatures Chamber'),'body-parts':t('Partes / Body Parts','Body Parts'),water:t('Água / Water','Water'),honeydew:t('Honeydew','Honeydew'),'food-processing':'Food Processing','leaf-storage':'Leaf Storage','seed-storage':'Seed Storage'}[id]||id.replaceAll('-',' '));return <div className="gd-link-group"><b>{title}</b>{ids.map(id=><a key={id} href={`#/${type}/${id}`}>{label(id)} <ChevronRight size={14}/></a>)}</div>}

function GuideDetail({guide}){
  const {language,t}=useLanguage();
  const [done,setDone]=useState(()=>{try{return JSON.parse(localStorage.getItem(progressKey(guide.id))||'{}')}catch{return{}}});
  useEffect(()=>{try{localStorage.setItem(progressKey(guide.id),JSON.stringify(done))}catch{}},[done,guide.id]);
  const count=guide.steps.filter((_,i)=>done[i]).length;
  return <div className="rdb-page rdb-detail-page gd-detail"><a className="rdb-back" href="#/guides"><ChevronLeft size={17}/>{t('Voltar para Guias','Back to Guides')}</a><section className="rdb-detail-hero gd-detail-hero"><div className="rdb-detail-icon">{guide.icon}</div><div className="rdb-detail-copy"><div className="rdb-detail-badges"><span>{categoryLabel(guide.category,t)}</span><span>{stageLabel(guide.stage,t)}</span><SourceBadge guide={guide} language={language}/></div><h1>{tr(guide.title,language)}</h1><p>{tr(guide.summary,language)}</p><div className="gd-outcome"><Target size={17}/><div><b>{t('Objetivo do guia','Guide outcome')}</b><span>{tr(guide.outcome,language)}</span></div></div></div></section>
  <section className="rdb-panel gd-progress"><div className="gd-panel-head"><div><span><Check size={16}/>{t('Passo a passo','Step by step')}</span><h2>{count}/{guide.steps.length} {t('concluídos','completed')}</h2></div><button type="button" onClick={()=>setDone({})}>{t('Resetar','Reset')}</button></div><div className="gd-step-list">{guide.steps.map((step,i)=><button type="button" key={i} className={done[i]?'done':''} onClick={()=>setDone(s=>({...s,[i]:!s[i]}))}><span>{done[i]?<Check size={16}/>:i+1}</span><p>{tr(step,language)}</p></button>)}</div></section>
  <div className="rdb-detail-grid"><section className="rdb-panel"><div className="gd-panel-head"><div><span><BookOpen size={16}/>{t('Antes de começar','Before you start')}</span></div></div><ul className="gd-simple-list">{guide.prerequisites.map((x,i)=><li key={i}>{tr(x,language)}</li>)}</ul></section><section className="rdb-panel gd-warning"><div className="gd-panel-head"><div><span><AlertTriangle size={16}/>{t('Evite isso','Avoid this')}</span></div></div><ul className="gd-simple-list">{guide.avoid.map((x,i)=><li key={i}>{tr(x,language)}</li>)}</ul></section></div>
  <section className="rdb-panel"><div className="gd-panel-head"><div><span><Waypoints size={16}/>{t('Continue daqui','Continue from here')}</span></div></div><div className="gd-related"><LinkGroup title={t('Recursos','Resources')} ids={guide.links.resources} type="resources" t={t}/><LinkGroup title={t('Câmaras','Chambers')} ids={guide.links.chambers} type="chambers" t={t}/><LinkGroup title={t('Mecânicas','Mechanics')} ids={guide.links.mechanics} type="mechanics" t={t}/><LinkGroup title={t('Criaturas','Creatures')} ids={guide.links.creatures} type="creatures" t={t}/></div></section>
  <a className="gd-source-link" href={guide.sourceUrl} target="_blank" rel="noreferrer"><BookOpen size={16}/>{t('Abrir fonte principal deste guia','Open this guide primary source')} <ExternalLink size={14}/></a></div>;
}

export default function GuideDatabasePage({routeId}){const guide=routeId?byId(routeId):null;if(routeId&&!guide)return <div className="rdb-page"><div className="rdb-empty"><AlertTriangle size={28}/><b>404</b><a href="#/guides">{routeId}</a></div></div>;return guide?<GuideDetail guide={guide}/>:<GuideList/>;}
