import React,{useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowRight,BookOpen,Calculator,Check,ChevronLeft,ChevronRight,Circle,ExternalLink,GitCompareArrows,ListChecks,RotateCcw,Search,ShieldCheck,Sparkles,Target,Wrench} from 'lucide-react';
import {useLanguage} from './LanguageProviderLite';
import {creatures,specialCreatures} from './wikiData';
import './resourceDatabasePage.css';
import './toolDatabasePage.css';

const TOOL_META={version:'0.1153',checkedAt:'2026-09-06'};
const TOOLS=[
  {id:'fusion',icon:'🧬',cat:'combat',title:['Calculadora de fusão','Fusion calculator'],desc:['Chance real com Chamber, Honeydew, Clan, Bluebells, skin e Gems.','Real chance with Chamber, Honeydew, Clan, Bluebells, skin and Gems.']},
  {id:'queen-resin',icon:'👑',cat:'progression',title:['Planner Queen ↔ Resin','Queen ↔ Resin planner'],desc:['Veja custo, tempo e qual Resin Chamber comporta o próximo upgrade.','See cost, time and which Resin Chamber can hold the next upgrade.']},
  {id:'farm',icon:'🌾',cat:'farm',title:['Planejador de farm','Farm planner'],desc:['Use sua média real para estimar runs e tempo sem inventar drop rate.','Use your real average to estimate runs and time without invented drop rates.']},
  {id:'battle-tokens',icon:'🎟️',cat:'combat',title:['Planner de Battle Tokens','Battle Token planner'],desc:['Planeje gastos e veja exatamente como o reset das 00:00 UTC afeta seu saldo.','Plan spending and see exactly how the 00:00 UTC reset affects your balance.']},
  {id:'daily',icon:'📅',cat:'routine',title:['Ganhos diários','Daily gains'],desc:['Some Daily Quests e co-ops fixos sem contar recompensa variável.','Add fixed Daily Quest and co-op rewards without counting variable rewards.']},
  {id:'legions',icon:'🛡️',cat:'late',title:['Planner de Legions','Legions planner'],desc:['Calcule quanto Resin e Silk falta para slots e novas espécies.','Calculate missing Resin and Silk for slots and new ant species.']},
  {id:'collection',icon:'🪲',cat:'tracker',title:['Tracker de coleção','Collection tracker'],desc:['Marque criaturas obtidas e mantenha o progresso salvo neste aparelho.','Mark owned creatures and keep progress saved on this device.']}
];
const SOURCE_URLS={fusion:'https://pocketants.fandom.com/wiki/Creatures',queen:'https://pocketants.fandom.com/wiki/Queen%27s_Chamber',resin:'https://pocketants.fandom.com/wiki/Resin_Chamber',tokens:'https://pocketants.fandom.com/wiki/Battle_Tokens',daily:'https://pocketants.fandom.com/wiki/Daily_Quests',coop:'https://pocketants.fandom.com/wiki/Co-op_Mode',legions:'https://pocketants.fandom.com/wiki/Legions'};
const QUEEN={2:[15,0,3/60],3:[75,0,1],4:[150,0,3],5:[350,0,6],6:[750,7500,12],7:[1000,10000,24],8:[2500,25000,48],9:[4000,40000,72],10:[6000,60000,168],11:[8000,80000,336],12:[9900,99000,672]};
const RESIN_STORAGE={1:3000,2:6000,3:9000,4:12000,5:20000,6:25000,7:40000,8:50000,9:60000,10:70000,11:80000,12:99999};
const FUSION_BASE={2:{1:75,2:80,3:85,4:90},3:{1:35,2:40,3:45,4:50},4:{1:1,2:5,3:10,4:15}};
const FUSION_HD={0:0,1:2,2:3,3:5,4:7,5:10};
const FUSION_COST={2:15,3:30,4:50};
const tr=(pair,lang)=>lang==='en'?pair[1]:pair[0];
const fmt=(n,lang)=>Number(n||0).toLocaleString(lang==='en'?'en-US':'pt-BR');
const readHeaderQuery=()=>new URLSearchParams((window.location.hash.split('?')[1]||'')).get('dbq')||'';

function ToolSource({href,t}){return <a className="td-source" href={href} target="_blank" rel="noreferrer"><BookOpen size={14}/>{t('Fonte','Source')}<ExternalLink size={12}/></a>}
function NumberField({label,value,onChange,min=0,max,step=1}){return <label className="td-field"><span>{label}</span><input type="number" inputMode="numeric" min={min} max={max} step={step} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function SelectField({label,value,onChange,children}){return <label className="td-field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{children}</select></label>}
function Result({label,value,sub}){return <div className="td-result"><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}

function FarmTool(){const {language,t}=useLanguage();const [current,setCurrent]=useState(0),[target,setTarget]=useState(5000),[perRun,setPerRun]=useState(250),[minutes,setMinutes]=useState(8);const missing=Math.max(0,+target-(+current));const runs=+perRun>0?Math.ceil(missing/(+perRun)):0;const total=runs*(+minutes||0);return <ToolFrame title={t('Planejador de farm','Farm planner')} icon="🌾" desc={t('A média vem de você, então a ferramenta continua útil mesmo se drops mudarem.','You provide the average, so the tool stays useful even if drops change.')}><div className="td-form-grid"><NumberField label={t('Tenho agora','Current')} value={current} onChange={setCurrent}/><NumberField label={t('Meta','Target')} value={target} onChange={setTarget}/><NumberField label={t('Ganho por run','Gain per run')} value={perRun} onChange={setPerRun} min={1}/><NumberField label={t('Minutos por run','Minutes per run')} value={minutes} onChange={setMinutes}/></div><div className="td-results"><Result label={t('Faltam','Remaining')} value={fmt(missing,language)}/><Result label="Runs" value={runs}/><Result label={t('Tempo estimado','Estimated time')} value={`${Math.floor(total/60)}h ${Math.round(total%60)}m`}/></div><p className="td-note">{t('Sem drop rate inventado: coloque sua média observada.','No invented drop rate: enter your observed average.')}</p></ToolFrame>}

function FusionTool(){const {t}=useLanguage();const [star,setStar]=useState('4'),[cc,setCc]=useState('4'),[hd,setHd]=useState('0'),[clan,setClan]=useState('0'),[blue,setBlue]=useState(false),[rock,setRock]=useState(false),[gem,setGem]=useState('0');const base=FUSION_BASE[+star][+cc];const bonus=FUSION_HD[+hd]+(+clan)+(blue?5:0)+(rock?1:0)+(+gem);const chance=Math.min(100,base+bonus);return <ToolFrame title={t('Calculadora de fusão','Fusion calculator')} icon="🧬" desc={t('Soma os bônus documentados sobre a chance base da Creatures Chamber.','Adds documented bonuses on top of the Creatures Chamber base chance.')} source={SOURCE_URLS.fusion}><div className="td-form-grid"><SelectField label={t('Fusão alvo','Fusion target')} value={star} onChange={setStar}><option value="2">1★ → 2★</option><option value="3">2★ → 3★</option><option value="4">3★ → 4★</option></SelectField><SelectField label="Creatures Chamber" value={cc} onChange={setCc}>{[1,2,3,4].map(x=><option key={x} value={x}>Lv.{x}</option>)}</SelectField><SelectField label="Honeydew Fusion Success" value={hd} onChange={setHd}>{[0,1,2,3,4,5].map(x=><option key={x} value={x}>Lv.{x} (+{FUSION_HD[x]}%)</option>)}</SelectField><SelectField label={t('Bônus de Clan','Clan bonus')} value={clan} onChange={setClan}><option value="0">0%</option><option value="2">+2%</option><option value="3">+3%</option><option value="5">+5%</option></SelectField><SelectField label={t('Boost de Gems','Gem boost')} value={gem} onChange={setGem}><option value="0">0%</option><option value="25">+25% · 300 💎</option><option value="50">+50% · 500 💎</option></SelectField></div><div className="td-toggle-row"><button className={blue?'active':''} onClick={()=>setBlue(v=>!v)} type="button">🌸 Bluebells +5%</button><button className={rock?'active':''} onClick={()=>setRock(v=>!v)} type="button">🪨 Rock skin +1%</button></div><div className="td-results"><Result label={t('Chance base','Base chance')} value={`${base}%`}/><Result label={t('Bônus','Bonuses')} value={`+${bonus}%`}/><Result label={t('Chance final','Final chance')} value={`${chance}%`} sub={chance===100?t('Limitada a 100%','Capped at 100%'):undefined}/><Result label="Body Parts" value={FUSION_COST[+star]}/></div></ToolFrame>}

function QueenResinTool(){const {language,t}=useLanguage();const [current,setCurrent]=useState('5'),[target,setTarget]=useState('10'),[resinLv,setResinLv]=useState('6');const from=Math.max(1,+current),to=Math.max(from+1,+target);const rows=Object.entries(QUEEN).filter(([lv])=>+lv>from&&+lv<=to);const seeds=rows.reduce((s,[,v])=>s+v[0],0),resin=rows.reduce((s,[,v])=>s+v[1],0),hours=rows.reduce((s,[,v])=>s+v[2],0);const peak=Math.max(0,...rows.map(([,v])=>v[1]));const minResin=Object.entries(RESIN_STORAGE).find(([,cap])=>cap>=peak)?.[0]||12;const cap=RESIN_STORAGE[+resinLv];const blocked=peak>cap;return <ToolFrame title={t('Planner Queen ↔ Resin','Queen ↔ Resin planner')} icon="👑" desc={t('Calcula upgrades da Queen e verifica se sua Resin Chamber comporta o maior custo individual.','Calculates Queen upgrades and checks whether your Resin Chamber can hold the largest single cost.')} source={SOURCE_URLS.queen}><div className="td-form-grid"><SelectField label={t('Queen atual','Current Queen')} value={current} onChange={setCurrent}>{Array.from({length:11},(_,i)=>i+1).map(x=><option key={x} value={x}>Lv.{x}</option>)}</SelectField><SelectField label={t('Queen alvo','Target Queen')} value={target} onChange={setTarget}>{Array.from({length:11},(_,i)=>i+2).map(x=><option key={x} value={x}>Lv.{x}</option>)}</SelectField><SelectField label={t('Resin Chamber atual','Current Resin Chamber')} value={resinLv} onChange={setResinLv}>{Array.from({length:12},(_,i)=>i+1).map(x=><option key={x} value={x}>Lv.{x} · {fmt(RESIN_STORAGE[x],language)}</option>)}</SelectField></div><div className="td-results"><Result label={t('Sementes totais','Total seeds')} value={fmt(seeds,language)}/><Result label={t('Resina total','Total resin')} value={fmt(resin,language)}/><Result label={t('Tempo total','Total time')} value={`${Math.floor(hours/24)}d ${Math.round(hours%24)}h`}/><Result label={t('Resin Chamber mínima','Minimum Resin Chamber')} value={`Lv.${minResin}`}/></div><div className={`td-status ${blocked?'bad':'good'}`}>{blocked?<AlertTriangle size={18}/>:<Check size={18}/>}<span>{blocked?t(`Sua Resin Chamber comporta ${fmt(cap,language)}, mas um upgrade exige até ${fmt(peak,language)}.`,`Your Resin Chamber holds ${fmt(cap,language)}, but one upgrade needs up to ${fmt(peak,language)}.`):t('Sua capacidade atual comporta o maior custo de Resin desse caminho.','Your current capacity can hold the largest Resin cost on this path.')}</span></div><div className="td-source-row"><ToolSource href={SOURCE_URLS.queen} t={t}/><ToolSource href={SOURCE_URLS.resin} t={t}/></div></ToolFrame>}

function TokenTool(){const {t}=useLanguage();const [current,setCurrent]=useState(3),[runs,setRuns]=useState(1);const spent=Math.max(0,+runs)*3;const after=Math.max(0,+current-spent);const reset=after<3?3:after;return <ToolFrame title={t('Planner de Battle Tokens','Battle Token planner')} icon="🎟️" desc={t('Cada entrada comum de dungeon/co-op usa 3 tokens; o reset só restaura saldos abaixo de 3.','Common dungeon/co-op entries use 3 tokens; reset only restores balances below 3.')} source={SOURCE_URLS.tokens}><div className="td-form-grid"><NumberField label={t('Tokens agora','Tokens now')} value={current} onChange={setCurrent}/><NumberField label={t('Entradas planejadas','Planned entries')} value={runs} onChange={setRuns}/></div><div className="td-results"><Result label={t('Custo','Cost')} value={`${spent} 🎟️`}/><Result label={t('Saldo depois','Balance after')} value={after}/><Result label={t('Após 00:00 UTC','After 00:00 UTC')} value={reset}/><Result label={t('Entradas possíveis agora','Entries possible now')} value={Math.floor((+current||0)/3)}/></div><p className="td-note">{t('Se terminar o dia com 0–2, volta para 3. Com 3 ou mais, o saldo permanece.','If you end the day with 0–2, it returns to 3. With 3 or more, the balance remains.')}</p></ToolFrame>}

function DailyTool(){const {language,t}=useLanguage();const defaults={quests:true,tp:false,tc:false,cp:false,cc:false,frog:false};const [done,setDone]=useState(defaults);const add=(k,v)=>done[k]?v:0;const resin=add('quests',1500)+add('tp',2000)+add('tc',2000);const honey=add('quests',150)+add('frog',250);const parts=add('cp',100)+add('cc',100);const gems=add('quests',10);const tokens=(done.tp?3:0)+(done.tc?3:0)+(done.cp?3:0)+(done.cc?3:0)+(done.frog?3:0);const options=[['quests',t('4 Daily Quests','4 Daily Quests')],['tp',t('Termite público','Public Termite')],['tc',t('Termite do clã','Clan Termite')],['cp',t('Crab público','Public Crab')],['cc',t('Crab do clã','Clan Crab')],['frog','Frog Pond']];return <ToolFrame title={t('Ganhos diários fixos','Fixed daily gains')} icon="📅" desc={t('Some apenas recompensas fixas conhecidas. Skins, drops variáveis e escolhas do Beehive ficam fora.','Adds only known fixed rewards. Skins, variable drops and Beehive choices are excluded.')} source={SOURCE_URLS.daily}><div className="td-check-grid">{options.map(([id,label])=><button type="button" key={id} className={done[id]?'active':''} onClick={()=>setDone(s=>({...s,[id]:!s[id]}))}>{done[id]?<Check size={16}/>:<Circle size={16}/>}<span>{label}</span></button>)}</div><div className="td-results"><Result label="Resin" value={fmt(resin,language)}/><Result label="Honeydew" value={fmt(honey,language)}/><Result label="Body Parts" value={fmt(parts,language)}/><Result label="Gems" value={fmt(gems,language)}/><Result label={t('Tokens gastos','Tokens spent')} value={tokens}/></div><div className="td-source-row"><ToolSource href={SOURCE_URLS.daily} t={t}/><ToolSource href={SOURCE_URLS.coop} t={t}/></div></ToolFrame>}

function LegionTool(){const {language,t}=useLanguage();const [slots,setSlots]=useState('1'),[carp,setCarp]=useState(false),[bullet,setBullet]=useState(false),[explode,setExplode]=useState(false),[resin,setResin]=useState(0),[silk,setSilk]=useState(0);const wanted=Math.max(1,+slots);const slotResin=50000;const slotSilk=Math.max(0,wanted-1)*5000;const speciesResin=carp?50000:0;const speciesSilk=(bullet?5000:0)+(explode?5000:0);const needR=slotResin+speciesResin,needS=slotSilk+speciesSilk;return <ToolFrame title={t('Planner de Legions','Legions planner')} icon="🛡️" desc={t('Planeje desbloqueios de slots e espécies sem misturar Resin com Silk.','Plan slot and species unlocks without mixing Resin and Silk.')} source={SOURCE_URLS.legions}><div className="td-form-grid"><SelectField label={t('Slots desejados','Desired slots')} value={slots} onChange={setSlots}>{[1,2,3,4].map(x=><option key={x} value={x}>{x}</option>)}</SelectField><NumberField label={t('Resin disponível','Available Resin')} value={resin} onChange={setResin}/><NumberField label={t('Silk disponível','Available Silk')} value={silk} onChange={setSilk}/></div><div className="td-toggle-row"><button className={carp?'active':''} onClick={()=>setCarp(v=>!v)}>🐜 Carpenter</button><button className={bullet?'active':''} onClick={()=>setBullet(v=>!v)}>🐜 Bullet</button><button className={explode?'active':''} onClick={()=>setExplode(v=>!v)}>💥 Exploding</button></div><div className="td-results"><Result label={t('Resin necessária','Resin needed')} value={fmt(needR,language)}/><Result label={t('Silk necessária','Silk needed')} value={fmt(needS,language)}/><Result label={t('Falta Resin','Missing Resin')} value={fmt(Math.max(0,needR-(+resin)),language)}/><Result label={t('Falta Silk','Missing Silk')} value={fmt(Math.max(0,needS-(+silk)),language)}/></div><p className="td-note">{t('O 1º slot custa 50.000 Resin; slots 2–4 custam 5.000 Silk cada. Carpenter usa Resin; Bullet e Exploding usam Silk.','The 1st slot costs 50,000 Resin; slots 2–4 cost 5,000 Silk each. Carpenter uses Resin; Bullet and Exploding use Silk.')}</p></ToolFrame>}

function CollectionTool(){const {t}=useLanguage();const all=useMemo(()=>[...creatures.map(c=>({id:c.id,name:c.name,kind:c.rarity})),...specialCreatures.map(c=>({id:c.id,name:c.name,kind:'Especial'}))],[]);const [owned,setOwned]=useState(()=>{try{return JSON.parse(localStorage.getItem('pa-collection')||'{}')}catch{return{}}});const [query,setQuery]=useState('');useEffect(()=>{try{localStorage.setItem('pa-collection',JSON.stringify(owned))}catch{}},[owned]);const filtered=all.filter(x=>x.name.toLowerCase().includes(query.toLowerCase()));const count=all.filter(x=>owned[x.id]).length;return <ToolFrame title={t('Tracker de coleção','Collection tracker')} icon="🪲" desc={t('Compatível com o tracker antigo: suas marcações continuam salvas neste aparelho.','Compatible with the old tracker: your marks remain saved on this device.')}><div className="td-collection-head"><label className="rdb-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('Filtrar criaturas…','Filter creatures…')}/></label><b>{count}/{all.length}</b></div><div className="td-collection">{filtered.map(x=><button type="button" key={x.id} className={owned[x.id]?'owned':''} onClick={()=>setOwned(s=>({...s,[x.id]:!s[x.id]}))}>{owned[x.id]?<Check size={16}/>:<Circle size={16}/>}<span><strong>{x.name}</strong><small>{x.kind}</small></span></button>)}</div></ToolFrame>}

function ToolFrame({title,icon,desc,source,children}){const {t}=useLanguage();return <div className="rdb-page td-detail"><a className="rdb-back" href="#/tools"><ChevronLeft size={17}/>{t('Voltar para Ferramentas','Back to Tools')}</a><section className="rdb-detail-hero td-hero"><div className="rdb-detail-icon">{icon}</div><div className="rdb-detail-copy"><div className="rdb-detail-badges"><span>{t('Ferramenta interativa','Interactive tool')}</span><span><ShieldCheck size={13}/>{t('Cálculo local','Local calculation')}</span></div><h1>{title}</h1><p>{desc}</p>{source&&<div className="rdb-detail-actions"><ToolSource href={source} t={t}/></div>}</div></section><section className="rdb-panel td-tool-body">{children}</section></div>}

const TOOL_COMPONENTS={'fusion':FusionTool,'queen-resin':QueenResinTool,'farm':FarmTool,'battle-tokens':TokenTool,'daily':DailyTool,'legions':LegionTool,'collection':CollectionTool};
function ToolHub(){const {language,t}=useLanguage();const [query,setQuery]=useState(readHeaderQuery);useEffect(()=>{const fn=()=>setQuery(readHeaderQuery());window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);const filtered=TOOLS.filter(x=>!query||`${tr(x.title,language)} ${tr(x.desc,language)} ${x.cat}`.toLowerCase().includes(query.toLowerCase()));return <div className="rdb-page td-page"><section className="rdb-identity"><div className="rdb-title-row"><span className="rdb-db-icon"><Wrench size={22}/></span><div><span className="rdb-kicker">{t('Ferramentas · resposta antes de planilha','Tools · answer before spreadsheet')}</span><h1>{t('Central de Ferramentas','Tools Hub')}</h1></div></div><p>{t('Calculadoras e trackers organizados por objetivo. Abra uma ferramenta por vez para manter a tela limpa e fácil de usar no celular.','Calculators and trackers organized by goal. Open one tool at a time to keep the screen clean and mobile-friendly.')}</p><div className="rdb-principles"><span><Calculator size={15}/>{t('Cálculo transparente','Transparent calculations')}</span><span><Target size={15}/>{t('Uma tarefa por vez','One task at a time')}</span><span><ShieldCheck size={15}/>{t('Fontes visíveis','Visible sources')}</span></div></section><section className="td-pick"><Sparkles size={19}/><div><b>{t('Escolha pelo que você quer resolver','Choose what you want to solve')}</b><span>{t('Progressão, farm, combate, rotina ou coleção.','Progression, farming, combat, routine or collection.')}</span></div></section><label className="rdb-search td-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('Buscar fusão, Resin, tokens, farm…','Search fusion, Resin, tokens, farming…')}/></label><section className="td-grid">{filtered.map(tool=><a className="td-card" href={`#/tools/${tool.id}`} key={tool.id}><span className="td-card-icon">{tool.icon}</span><div><small>{tool.cat}</small><h2>{tr(tool.title,language)}</h2><p>{tr(tool.desc,language)}</p></div><ChevronRight size={18}/></a>)}</section><section className="td-trust"><BookOpen size={18}/><div><b>{t(`Base ${TOOL_META.version} · revisada em 06/09/2026`,`Database ${TOOL_META.version} · reviewed 2026-09-06`)}</b><span>{t('Quando uma recompensa é variável, a ferramenta não inventa um valor médio escondido.','When a reward is variable, the tool does not invent a hidden average value.')}</span></div></section></div>}

export default function ToolDatabasePage({routeId}){if(!routeId)return <ToolHub/>;const C=TOOL_COMPONENTS[routeId];if(!C)return <div className="rdb-page"><div className="rdb-empty"><AlertTriangle size={28}/><b>404</b><a href="#/tools">{routeId}</a></div></div>;return <C/>;}
